version: "6.8"
policies:
  - fields:
    - localip
    - remoteip
  - fields:
    - localip
    - recipientdomain
  - fields:
    - localip
    - grouping
  - fields:
    - localip
    - recipientdomain
    - grouping