version: "5.8"
servers:
  - id: default
    transport: mx
    phases:
      eod:
        hook: default
transportgroups:
  - id: default
    connection:
      sourceip:
        ipv6: false
    retry:
      count: 30
      intervals:
        - interval: 60
        - interval: 900
        - interval: 3600
        - interval: 7200
        - interval: 10800
    transports:
      - id: mx
        session:
          tls:
            mode: dane
resolver:
  cache:
    size: 10000
plugins:
  - id: warmup
    config:
      ips:
        - ip: 10.1.1.1
          class: slow_warmup
          added: "2021-03-10"