version: "6.8"
servers:
  - id: default
    transport: mx
    phases:
      eod:
        hook: default
transportgroups:
  - id: default
    connection:
      sourceip:
        ipv6: false
    retry:
      count: 30
      intervals:
        - interval: 60
        - interval: 900
        - interval: 3600
        - interval: 7200
        - interval: 10800
    transports:
      - id: mx
        session:
          tls:
            mode: dane
resolver:
  cache:
    size: 10000
queues:
  grouping:
    default: recipientdomain
    groupings:
      - id: google
        remotemx:
          - "*.google.com"
          - "*.googlemail.com"
          - "*.smtp.goog"
addresses:
  - id: warm_ip_1
    address: "10.1.1.2"
plugins:
  - id: warmup
    config:
      exclude: true
      schedules:
        - class: slow_warmup
          fields:
            - localip
            - recipientdomain: "gmail.com"
            - grouping: "&google"
          interval: 3600
          ratealgorithm: fixedwindow
          schedule:
            - day: 0
              messages: 10
            - day: 1
              messages: 20
            - day: 2
              messages: 30
            - day: 3
              messages: 40
      ips:
        - ip: "10.1.1.1"
          class: slow_warmup
          added: "2026-06-18"